In [1]:
from PIL import Image
import os, glob, numpy as np
from sklearn.model_selection import train_test_split

caltech_dir = "C:/Users/ICT01_20/Desktop/food-5"
categories  = os.listdir(caltech_dir)
nb_classes = len(categories )
image_w = 128
image_h = 128

X = []
y = []

In [2]:
import numpy as np
for idx, cat in enumerate(categories):
    
    #one-hot 돌리기.
    label = [0 for i in range(nb_classes)]
    label[idx] = 1

    image_dir = caltech_dir + "/" + cat
    files = glob.glob(image_dir+"/*.JPG")
    print(cat, " 파일 길이 : ", len(files))
    for i, f in enumerate(files):
        img = Image.open(f)
        img = img.convert("RGB")
        img = img.resize((image_w, image_h))
        data = np.asarray(img)

        X.append(data)
        y.append(label)

        if i % 700 == 0:
            print(cat, " : ", f)

X = np.array(X)
y = np.array(y)

train_ratio = 0.60
validation_ratio = 0.20
test_ratio = 0.20

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1 - train_ratio)

X_val, X_test, y_val, y_test = train_test_split(X_test, y_test, test_size=test_ratio/(test_ratio + validation_ratio))
xy = (X_train, X_test, X_val , y_train, y_test,y_val )
np.save("C:/Users/ICT01_20/Desktop/food-5-2", xy)

print("ok", len(y))

계란찜  파일 길이 :  784
계란찜  :  C:/Users/ICT01_20/Desktop/food-5/계란찜\Img_125_0000.jpg
계란찜  :  C:/Users/ICT01_20/Desktop/food-5/계란찜\Img_125_0871.jpg
고사리나물  파일 길이 :  896
고사리나물  :  C:/Users/ICT01_20/Desktop/food-5/고사리나물\Img_041_0000.JPG
고사리나물  :  C:/Users/ICT01_20/Desktop/food-5/고사리나물\Img_041_0782.jpg
삼계탕  파일 길이 :  864
삼계탕  :  C:/Users/ICT01_20/Desktop/food-5/삼계탕\Img_138_0000.jpg
삼계탕  :  C:/Users/ICT01_20/Desktop/food-5/삼계탕\Img_138_0785.jpg
오징어채볶음  파일 길이 :  704
오징어채볶음  :  C:/Users/ICT01_20/Desktop/food-5/오징어채볶음\Img_087_0003.jpg
오징어채볶음  :  C:/Users/ICT01_20/Desktop/food-5/오징어채볶음\Img_087_1070.jpg
콩자반  파일 길이 :  675
콩자반  :  C:/Users/ICT01_20/Desktop/food-5/콩자반\Img_025_0001.jpg
ok 3923


In [3]:
print(X_val.shape)
print(X_train.shape)
print(X_test.shape)

(785, 128, 128, 3)
(2353, 128, 128, 3)
(785, 128, 128, 3)


In [6]:
print(X_val)
print('---------------------------',X_train)

[[[[0.00392157 0.00392157 0.00392157]
   [0.00392157 0.00392157 0.00392157]
   [0.00392157 0.00392157 0.00392157]
   ...
   [0.00392157 0.00392157 0.00392157]
   [0.00392157 0.00392157 0.00392157]
   [0.00392157 0.00392157 0.00392157]]

  [[0.00392157 0.00392157 0.00392157]
   [0.00392157 0.00392157 0.00392157]
   [0.00392157 0.00392157 0.00392157]
   ...
   [0.00392157 0.00392157 0.00392157]
   [0.00392157 0.00392157 0.00392157]
   [0.00392157 0.00392157 0.00392157]]

  [[0.00392157 0.00392157 0.00392157]
   [0.00392157 0.00392157 0.00392157]
   [0.00392157 0.00392157 0.00392157]
   ...
   [0.00392157 0.00392157 0.00392157]
   [0.00392157 0.00392157 0.00392157]
   [0.00392157 0.00392157 0.00392157]]

  ...

  [[0.00392157 0.00392157 0.00392157]
   [0.00392157 0.00392157 0.00392157]
   [0.00392157 0.00392157 0.00392157]
   ...
   [0.00392157 0.00392157 0.00392157]
   [0.00392157 0.00392157 0.00392157]
   [0.00392157 0.00392157 0.00392157]]

  [[0.00392157 0.00392157 0.00392157]
   [0.0

In [5]:
print(y_val.shape)
print(y_train.shape)
print(y_test.shape)

(785, 5)
(2353, 5)
(785, 5)


In [4]:
import os, glob, numpy as np
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Dense, Flatten, Dropout
from keras.callbacks import EarlyStopping, ModelCheckpoint
import matplotlib.pyplot as plt
import keras.backend.tensorflow_backend as K
#np_load_old = np.load
#np.load = lambda *a, **k : np_load_old(*a, allow_pickle=True, **k)
#np.load = np_load_old

import tensorflow as tf
config = tf.ConfigProto()
config.gpu_options.allow_growth = True
session = tf.Session(config=config)

X_train, X_test, X_val , y_train, y_test, y_val= np.load('C:/Users/ICT01_20/Desktop/food-5-2.npy',allow_pickle=True
)
print(X_train.shape)
print(X_train.shape[0])

Using TensorFlow backend.


(2353, 128, 128, 3)
2353


In [5]:
#일반화
X_train = X_train.astype(float) / 255
X_test = X_test.astype(float) / 255
X_val = X_test.astype(float) / 255

In [7]:
from keras.layers import BatchNormalization
with K.tf_ops.device('/device:GPU:0'):
    model = Sequential()
    model.add(Conv2D(32, (3,3), padding="same", input_shape=X_train.shape[1:], activation='relu')) 
    model.add(MaxPooling2D(pool_size=(2,2)))
    model.add(Dropout(0.25))
    
    model.add(Conv2D(64, (3,3), padding="same", activation='relu'))
    
    model.add(MaxPooling2D(pool_size=(2,2)))
    model.add(Dropout(0.25))
    
    model.add(Flatten())
    
    model.add(Dense(256, activation='relu'))
    model.add(Dropout(0.5))
    model.add(Dense(nb_classes, activation='softmax'))
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    model_dir = './test'
    
    if not os.path.exists(model_dir):
        os.mkdir(model_dir)
    
    model_path = model_dir + '/food5.model'
    checkpoint = ModelCheckpoint(filepath=model_path , monitor='val_loss', verbose=1, save_best_only=True)
    early_stopping = EarlyStopping(monitor='val_loss', patience=6)






Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.




In [18]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_3 (Conv2D)            (None, 128, 128, 32)      896       
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 64, 64, 32)        0         
_________________________________________________________________
dropout_4 (Dropout)          (None, 64, 64, 32)        0         
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 64, 64, 64)        18496     
_________________________________________________________________
max_pooling2d_4 (MaxPooling2 (None, 32, 32, 64)        0         
_________________________________________________________________
dropout_5 (Dropout)          (None, 32, 32, 64)        0         
_________________________________________________________________
flatten_2 (Flatten)          (None, 65536)             0         
__________

In [9]:
history = model.fit(X_train, y_train, batch_size=10, epochs=20, validation_data=(X_test, y_test), 
                    callbacks=[checkpoint, early_stopping])

Train on 2353 samples, validate on 785 samples
Epoch 1/20
2353/2353 [==============================] - 13s 5ms/step - loss: 0.0447 - acc: 0.9860 - val_loss: 0.3291 - val_acc: 0.9006

Epoch 00001: val_loss improved from 3.01411 to 0.32909, saving model to ./test/food5.model
Epoch 2/20
2353/2353 [==============================] - 13s 5ms/step - loss: 0.0827 - acc: 0.9703 - val_loss: 0.3479 - val_acc: 0.8917

Epoch 00002: val_loss did not improve from 0.32909
Epoch 3/20
2353/2353 [==============================] - 12s 5ms/step - loss: 0.0555 - acc: 0.9839 - val_loss: 0.3302 - val_acc: 0.9045

Epoch 00003: val_loss did not improve from 0.32909
Epoch 4/20
2353/2353 [==============================] - 12s 5ms/step - loss: 0.0621 - acc: 0.9754 - val_loss: 0.3982 - val_acc: 0.8904

Epoch 00004: val_loss did not improve from 0.32909
Epoch 5/20
2353/2353 [==============================] - 13s 5ms/step - loss: 0.0453 - acc: 0.9839 - val_loss: 0.4645 - val_acc: 0.8739

Epoch 00005: val_loss did not